# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MonaLista' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MonaLista

  target 'MonaListaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MonaListaUITests' do
    # Pods for testing
  end

end
